using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;

namespace EducationPlatform.IntegrationTests;

public sealed class ApiSmokeTests : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly HttpClient _client;
    public ApiSmokeTests(WebApplicationFactory<Program> factory) => _client = factory.WithWebHostBuilder(builder => builder.ConfigureAppConfiguration((_, config) => config.AddInMemoryCollection(new Dictionary<string, string?> { ["BackgroundJobs:Enabled"] = "false" }))).CreateClient(new WebApplicationFactoryClientOptions { AllowAutoRedirect = false, BaseAddress = new Uri("https://localhost") });
    [Fact] public async Task Swagger_document_is_available() { var response = await _client.GetAsync("/swagger/v1/swagger.json"); Assert.Equal(HttpStatusCode.OK, response.StatusCode); Assert.Contains("/api/v1/auth/login", await response.Content.ReadAsStringAsync()); }
    [Fact] public async Task Swagger_is_grouped_by_consumer_role() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); foreach (var tag in new[] { "Authentication", "Student APIs", "Teacher APIs", "Admin, Moderator & Partner APIs", "Shared APIs" }) Assert.Contains(tag, json); }
    [Fact] public async Task Swagger_exposes_teacher_assignments_page_endpoints() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); Assert.Contains("/api/v1/assignments/teacher-overview", json); Assert.Contains("/api/v1/submissions/teacher-view", json); }
    [Fact] public async Task Swagger_exposes_home_cards_and_schedule_endpoints() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); Assert.Contains("/api/v1/home/cards", json); Assert.Contains("/api/v1/home/schedule", json); Assert.Contains("zoomUrl", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Attendance_list_exposes_student_teacher_and_subject_names() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); Assert.Contains("AttendanceListItemResponse", json); Assert.Contains("studentName", json, StringComparison.OrdinalIgnoreCase); Assert.Contains("teacherName", json, StringComparison.OrdinalIgnoreCase); Assert.Contains("subjectName", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Swagger_exposes_session_crud_recurrence_and_session_backed_schedule() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); using var document = System.Text.Json.JsonDocument.Parse(json); var paths = document.RootElement.GetProperty("paths"); var session = paths.GetProperty("/api/v1/sessions/{id}"); Assert.True(session.TryGetProperty("put", out _)); Assert.True(session.TryGetProperty("delete", out _)); var schedules = paths.GetProperty("/api/v1/schedules"); Assert.True(schedules.TryGetProperty("get", out var scheduleGet)); Assert.False(schedules.TryGetProperty("post", out _)); var scheduleTags = scheduleGet.GetProperty("tags").EnumerateArray().Select(x => x.GetString()).ToArray(); Assert.Contains("Student APIs", scheduleTags); Assert.Contains("Teacher APIs", scheduleTags); Assert.Contains("Admin, Moderator & Partner APIs", scheduleTags); Assert.Contains("recurrenceType", json, StringComparison.OrdinalIgnoreCase); Assert.DoesNotContain("zoomMeetingUrl", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Anonymous_user_cannot_modify_session() { var response = await _client.PutAsJsonAsync($"/api/v1/sessions/{Guid.NewGuid()}", new { }); Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode); }
    [Fact] public async Task Login_contract_includes_full_name_and_roles() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); Assert.Contains("CurrentUserResponse", json); Assert.Contains("fullName", json, StringComparison.OrdinalIgnoreCase); Assert.Contains("roles", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Teacher_get_contract_includes_stage_rates_subjects_and_curricula() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); Assert.Contains("TeacherResponse", json); Assert.Contains("stageRates", json, StringComparison.OrdinalIgnoreCase); Assert.Contains("subjects", json, StringComparison.OrdinalIgnoreCase); Assert.Contains("curricula", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Supervision_schedule_supports_single_day_filter() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); using var document = System.Text.Json.JsonDocument.Parse(json); var parameters = document.RootElement.GetProperty("paths").GetProperty("/api/v1/schedules").GetProperty("get").GetProperty("parameters").EnumerateArray(); Assert.Contains(parameters, x => string.Equals(x.GetProperty("name").GetString(), "date", StringComparison.OrdinalIgnoreCase)); }
    [Fact] public async Task Supervision_has_dedicated_daily_schedule_shape() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); Assert.Contains("/api/v1/schedules/daily", json); Assert.Contains("DailySupervisionScheduleResponse", json); Assert.Contains("classLink", json, StringComparison.OrdinalIgnoreCase); Assert.Contains("studentName", json, StringComparison.OrdinalIgnoreCase); Assert.Contains("teacherName", json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Attendance_request_is_available_to_students_and_teachers() { var json = await _client.GetStringAsync("/swagger/v1/swagger.json"); using var document = System.Text.Json.JsonDocument.Parse(json); var tags = document.RootElement.GetProperty("paths").GetProperty("/api/v1/attendance/requests").GetProperty("post").GetProperty("tags").EnumerateArray().Select(x => x.GetString()).ToArray(); Assert.Contains("Student APIs", tags); Assert.Contains("Teacher APIs", tags); }
    [Fact] public async Task Protected_student_endpoint_rejects_anonymous_access() { var response = await _client.GetAsync("/api/v1/students"); Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode); }
    [Fact] public async Task Liveness_does_not_require_database() { var response = await _client.GetAsync("/health/live"); Assert.Equal(HttpStatusCode.OK, response.StatusCode); }
}
